# Generated by Django 5.2.15 on 2026-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PARTIAL', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='UNPAID', max_length=10),
        ),
    ]
