# Generated by Django 5.2.15 on 2026-06-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
